name: Vista Films
favicon: null
layout_spectrum: 0.7976909885182977
typography_spectrum: 0.20217261067591608
title: Vista Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.359635143307969
  lightness: 0.6557561645749956
  saturation: 0.5553340173792094
  rhythmicContrast: 0.6981340541969985
purpose: []
