name: Vista Films
favicon: null
layout_spectrum: 0.50835
typography_spectrum: 0.45826
title: Vista Films
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f7f8fa'
    - '#d4d2df'
    - '#5a383e'
    - '#6a657f'
    - '#d97f3f'
  brandStrength: 0.359635143307969
  lightness: 0.4375
  saturation: 0.5553340173792094
  rhythmicContrast: 0.6981340541969985
purpose: []
